django_blog/blog/urls.py
from django.contrib import admin
from django.urls import path
from .views import RegisterView, profile_view
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic.base import TemplateView
from .views import (
    PostDetailView,
    update_profile,
    UpdateProfileView,
    PostListView,
    PostEditView,
    PostDeleteView,
    CommentCreateView,
    CommentUpdateView,
    CommentDeleteView,
    PostCreateView,
    PostByTagListView,
)
from .views import search_posts

urlpatterns = [
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("profile/", profile_view, name="profile"),
    path(
        "profile/<int:pk>/update/", UpdateProfileView.as_view(), name="profile-update"
    ),
    path("", TemplateView.as_view(template_name="blog/home.html"), name="home"),
    path("login/", LoginView.as_view(template_name="blog/login.html"), name="login"),
    # CRUD for posts
    path("posts/", PostListView.as_view(), name="posts"),
    path("post/new/", PostCreateView.as_view(), name="posts-new"),
    path("post/<int:pk>", PostDetailView.as_view(), name="posts-details"),
    path("post/<int:pk>/update/", PostEditView.as_view(), name="posts-edit"),
    path("post/<int:pk>/delete/", PostDeleteView.as_view(), name="posts-delete"),
    # CRUD for comments
    path(
        "post/<int:pk>/comments/new/",
        CommentCreateView.as_view(),
        name="comment-update",
    ),
    path(
        "comment/<int:pk>/update/", CommentUpdateView.as_view(), name="comment-update"
    ),
    path(
        "comment/<int:pk>/delete/", CommentDeleteView.as_view(), name="comment-delete"
    ),
    path("search/", search_posts, name="search_posts"),
    path("tags/<slug:tag_slug>/", PostByTagListView.as_view(), name="posts_by_tag"),
]

django_blog/django_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls")),
]

django_blog/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    published_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="author")
    tags = TaggableManager()


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="post")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="author_name"
    )
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)


""" class Tag(models.Model):
    name = models.CharField(max_length=255)
    tags = models.ManyToManyField(Post, related_name="tags") """

django_blog/blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Comment
from .models import Post
from taggit.forms import TagWidget  # Import du widget pour gérer les tags


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content", "tags"]
        widgets = {
            "tags": TagWidget(),  # Utilisation du widget pour afficher les tags correctement
        }


class UserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True, label="Email")

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)

    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name"]

    def clean_email(self):
        username = self.cleaned_data.get("username")
        email = self.cleaned_data.get("email")

        if (
            email
            and User.objects.filter(email=email).exclude(username=username).count()
        ):
            raise forms.ValidationError(
                "This email address is already in use. Please supply a different email address."
            )
        return email

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]

        if commit:
            user.save()

        return user


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]

django_blog/blog/views.py
from django.views.generic import (
    CreateView,
    UpdateView,
    ListView,
    DetailView,
    DeleteView,
)
from .forms import UserCreationForm, UpdateUserForm
from django.urls import reverse_lazy, reverse
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from .models import Post
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q


# Create your views here.
class RegisterView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "blog/register.html"


@login_required(login_url="/blog/login/")
def profile_view(request):
    # This view can only be accessed by authenticated users
    return render(request, "blog/profile.html")


def logout_view(request):
    logout(request)
    return render(request, "blog/logout.html")


def update_profile(request, pk):

    user = get_object_or_404(User, id=pk)
    user = User.objects.get(id=pk)
    form = UpdateUserForm(request.POST, instance=user)
    if request.method == "POST":
        user.email = request.POST.get("email")
        user.username = request.POST.get("username")
        user.save()
        return HttpResponseRedirect("/blog/profile/")
    else:
        form = UpdateUserForm(instance=user)
    context = {"form": form, "user": user}
    return render(request, "blog/update_profile.html", context)


class UpdateProfileView(UpdateView):
    model = User
    template_name = "blog/update_profile.html"
    fields = ["first_name", "last_name", "username", "email"]
    success_url = reverse_lazy("profile")


# Use Django’s class-based views to handle CRUD operations:


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ["title", "content"]


class PostListView(ListView):
    model = Post
    queryset = Post.objects.all()
    paginate_by = 10
    template_name = "blog/post_list.html"


class PostDetailView(DetailView):
    model = Post
    template_name = "blog/post_details.html"


class PostEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ["title", "content"]
    template_name = "blog/post_update_form.html"

    def test_func(self):
        return self.get_object().author == self.request.user

    def get_success_url(self):
        return reverse_lazy("posts-details", args=[self.get_object().id])


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy("posts")

    def test_func(self):
        return self.get_object().author == self.request.user


class CommentCreateView(LoginRequiredMixin, CreateView):
    pass


class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    def test_func(self):
        return self.get_object().author == self.request.user


class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):

    def test_func(self):
        return self.get_object().author == self.request.user


def search_posts(request):
    query = request.GET.get("q")
    results = []

    if query:
        results = Post.objects.filter(
            Q(title__icontains=query)
            | Q(content__icontains=query)
            | Q(tags__name__icontains=query)
        ).distinct()

    return render(
        request, "blog/search_results.html", {"results": results, "query": query}
    )


from taggit.models import Tag


class PostByTagListView(ListView):
    model = Post
    template_name = "blog/posts_by_tag.html"
    context_object_name = "posts"

    def get_queryset(self):
        self.tag = get_object_or_404(Tag, slug=self.kwargs["tag_slug"])
        return Post.objects.filter(tags=self.tag)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tag"] = self.tag  # Ajouter le tag au contexte pour l'affichage
        return context

django_blog/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Django Blog{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
    <header>
        <nav>
            <ul>
                <li><a href="{% url 'register' %}">Register</a></li>
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'login' %}">Login</a></li>
                <li><a href="{% url 'profile' %}">Profile</a></li>
                <li><a href="{% url 'posts' %}">Blog Posts</a></li>
            </ul>
        </nav>
    </header>
    <form method="GET" action="{% url 'search_posts' %}">
        <input type="text" name="q" placeholder="Rechercher un article...">
        <button type="submit">Rechercher</button>
    </form>


    <div class="content">
        {% block content %}
        <!-- Page-specific content goes here -->
        {% endblock %}
    </div>

    <footer>
        <p>&copy; 2024 Django Blog</p>
    </footer>

    <script src="{% static 'js/scripts.js' %}"></script>
</body>

</html>

django_blog/blog/templates/blog/home.html
{% extends "blog/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
Hi !!! You are logged in as {{ user }}.
<form action="{% url 'logout' %}" method="post">
    {% csrf_token %}
    <button type="submit">Log Out</button>
</form>
{% else %}
<p>You are not logged in</p>
<a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}

django_blog/blog/templates/blog/login.html
{% extends "blog/base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}
<h2>Log In</h2>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Log In</button>
</form>
{% endblock %}

django_blog/blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}

{% block title %}Suppression{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete the post named " <strong>{{ object.title }}</strong>"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>
{% endblock %}

django_blog/blog/templates/blog/post_details.html
{% extends "blog/base.html" %}

{% block title %}Posts{% endblock %}

{% block content %}
<p>Tags:
    {% for tag in post.tags.all %}
    <a href="{% url 'posts_by_tag' tag.slug %}">{{ tag.name }}</a>{% if not forloop.last %}, {% endif %}
    {% endfor %}
</p>

<h1>{{ object.title|safe }}</h1>
<hr>
<p>{{ object.content|safe }}</p>
<li>{{ object.published_date|date }}</li>
<li>Author {{ object.author.username|safe }}</li>
<a href="{% url 'posts-edit' object.id %}">
    <button>Modifier</button>
</a>
{% endblock %}

django_blog/blog/templates/blog/post_form.html
{% extends "blog/base.html" %}

{% block title %}Add new post{% endblock %}

{% block content %}
<h2>Add new post</h2>
<label for="id_tags">Tags:</label>
<input type="text" name="tags" id="id_tags" value="{{ form.tags.value|default_if_none:'' }}"
    placeholder="Séparez les tags par des virgules">

<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Send</button>
</form>
{% endblock %}

django_blog/blog/templates/blog/post_list.html
{% extends "blog/base.html" %}

{% block title %}Posts{% endblock %}

{% block content %}
<a href="{% url 'posts-new' %}">
    <button>Add new post</button>
</a>
<br />
<br />
{% for post in object_list %}
<li>{{ post.id }}</li>
<h1>{{ post.title|safe }}</h1>
<hr>
<p>{{ post.content|safe }}</p>
<li>{{ post.published_date|date }}</li>
<li>Author {{ post.author.username|safe }}</li>

<a href="{% url 'posts-details' post.id %}">
    <button>Voir details</button>
</a>
<a href="{% url 'posts-edit' post.id %}">
    <button>Modifier</button>
</a>
<a href="{% url 'posts-delete' post.id %}">
    <button>Supprimer</button>
</a>
<br />
<br />


{% endfor %}

{% endblock %}

django_blog/blog/templates/blog/post_update_form.html
{% extends "blog/base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update post">
</form>
{% endblock %}

django_blog/blog/templates/blog/posts_by_tag.html
{% extends "base.html" %}

{% block content %}
<h2>Articles avec le tag "{{ tag }}"</h2>
{% for post in posts %}
<h3><a href="{% url 'post_detail' post.id %}">{{ post.title }}</a></h3>
<p>{{ post.content|truncatewords:30 }}</p>
{% empty %}
<p>Aucun article trouvé.</p>
{% endfor %}
{% endblock %}

django_blog/blog/templates/blog/profile.html
{% extends "blog/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<h2>Hi, welcome!!!</h2>
<p><strong>User ID:</strong> {{ user.id }}</p>
<p><strong>First name:</strong> {{ user.first_name }}</p>
<p><strong>Last name:</strong> {{ user.last_name }}</p>
<p><strong>Username:</strong> {{ user.username }}</p>
<p><strong>Email:</strong> {{ user.email }}</p>

<a href="{% url 'profile-update' user.id %}">
    <button>Update Profile</button>
</a>

<form action="{% url 'logout' %}" method="post">
    {% csrf_token %}
    <button type="submit">Log Out</button>
</form>
{% else %}
<p>You are not logged in.</p>
{% endif %}
{% endblock %}

django_blog/blog/templates/blog/register.html
{% extends "blog/base.html" %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<h2>Sign up</h2>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Sign Up</button>
</form>
{% endblock %}

django_blog/blog/templates/blog/search_results.html
{% extends "blog/base.html" %}

{% block content %}
<h2>Résultats de recherche pour "{{ query }}"</h2>
{% for post in results %}
<h3><a href="{% url 'posts-details' post.id %}">{{ post.title }}</a></h3>
<p>{{ post.content|truncatewords:30 }}</p>
{% empty %}
<p>Aucun résultat trouvé.</p>
{% endfor %}
{% endblock %}

django_blog/blog/templates/blog/update_profile.html
{% extends "blog/base.html" %}

{% block title %}Update profile{% endblock %}

{% block content %}

<h2>Update user infos</h2>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">UPDATE</button>
</form>
{% endblock %}